graph [
	comment "Generated by Search Analyser"
	comment "? Mauro Bampo 2008"
	directed 0
	isplanar 1
	node [
		id 0
		label "N0"
	]
	node [
		id 1
		label "N1"
	]
	node [
		id 3
		label "N3"
	]
	node [
		id 6
		label "N6"
	]
	node [
		id 19
		label "N19"
	]
	node [
		id 45
		label "N45"
	]
	node [
		id 2
		label "N2"
	]
	node [
		id 46
		label "N46"
	]
	node [
		id 50
		label "N50"
	]
	node [
		id 4
		label "N4"
	]
	node [
		id 5
		label "N5"
	]
	node [
		id 53
		label "N53"
	]
	node [
		id 7
		label "N7"
	]
	node [
		id 10
		label "N10"
	]
	node [
		id 14
		label "N14"
	]
	node [
		id 20
		label "N20"
	]
	node [
		id 23
		label "N23"
	]
	node [
		id 37
		label "N37"
	]
	node [
		id 47
		label "N47"
	]
	node [
		id 49
		label "N49"
	]
	node [
		id 51
		label "N51"
	]
	node [
		id 52
		label "N52"
	]
	node [
		id 54
		label "N54"
	]
	node [
		id 55
		label "N55"
	]
	node [
		id 57
		label "N57"
	]
	node [
		id 58
		label "N58"
	]
	node [
		id 8
		label "N8"
	]
	node [
		id 59
		label "N59"
	]
	node [
		id 74
		label "N74"
	]
	node [
		id 11
		label "N11"
	]
	node [
		id 12
		label "N12"
	]
	node [
		id 15
		label "N15"
	]
	node [
		id 17
		label "N17"
	]
	node [
		id 21
		label "N21"
	]
	node [
		id 22
		label "N22"
	]
	node [
		id 75
		label "N75"
	]
	node [
		id 24
		label "N24"
	]
	node [
		id 26
		label "N26"
	]
	node [
		id 36
		label "N36"
	]
	node [
		id 38
		label "N38"
	]
	node [
		id 39
		label "N39"
	]
	node [
		id 48
		label "N48"
	]
	node [
		id 56
		label "N56"
	]
	node [
		id 9
		label "N9"
	]
	node [
		id 60
		label "N60"
	]
	node [
		id 13
		label "N13"
	]
	node [
		id 16
		label "N16"
	]
	node [
		id 18
		label "N18"
	]
	node [
		id 25
		label "N25"
	]
	node [
		id 76
		label "N76"
	]
	node [
		id 78
		label "N78"
	]
	node [
		id 81
		label "N81"
	]
	node [
		id 27
		label "N27"
	]
	node [
		id 28
		label "N28"
	]
	node [
		id 40
		label "N40"
	]
	node [
		id 41
		label "N41"
	]
	node [
		id 42
		label "N42"
	]
	node [
		id 61
		label "N61"
	]
	node [
		id 63
		label "N63"
	]
	node [
		id 77
		label "N77"
	]
	node [
		id 79
		label "N79"
	]
	node [
		id 80
		label "N80"
	]
	node [
		id 82
		label "N82"
	]
	node [
		id 84
		label "N84"
	]
	node [
		id 86
		label "N86"
	]
	node [
		id 29
		label "N29"
	]
	node [
		id 30
		label "N30"
	]
	node [
		id 87
		label "N87"
	]
	node [
		id 43
		label "N43"
	]
	node [
		id 44
		label "N44"
	]
	node [
		id 62
		label "N62"
	]
	node [
		id 64
		label "N64"
	]
	node [
		id 65
		label "N65"
	]
	node [
		id 83
		label "N83"
	]
	node [
		id 85
		label "N85"
	]
	node [
		id 31
		label "N31"
	]
	node [
		id 34
		label "N34"
	]
	node [
		id 88
		label "N88"
	]
	node [
		id 66
		label "N66"
	]
	node [
		id 72
		label "N72"
	]
	node [
		id 32
		label "N32"
	]
	node [
		id 35
		label "N35"
	]
	node [
		id 67
		label "N67"
	]
	node [
		id 69
		label "N69"
	]
	node [
		id 73
		label "N73"
	]
	node [
		id 33
		label "N33"
	]
	node [
		id 68
		label "N68"
	]
	node [
		id 70
		label "N70"
	]
	node [
		id 71
		label "N71"
	]
	edge [
		source 0
		target 1
	]
	edge [
		source 0
		target 3
	]
	edge [
		source 0
		target 6
	]
	edge [
		source 0
		target 19
	]
	edge [
		source 0
		target 45
	]
	edge [
		source 1
		target 2
	]
	edge [
		source 1
		target 46
	]
	edge [
		source 1
		target 50
	]
	edge [
		source 3
		target 4
	]
	edge [
		source 3
		target 5
	]
	edge [
		source 3
		target 53
	]
	edge [
		source 6
		target 7
	]
	edge [
		source 6
		target 10
	]
	edge [
		source 6
		target 14
	]
	edge [
		source 19
		target 20
	]
	edge [
		source 19
		target 23
	]
	edge [
		source 19
		target 37
	]
	edge [
		source 46
		target 47
	]
	edge [
		source 46
		target 49
	]
	edge [
		source 50
		target 51
	]
	edge [
		source 50
		target 52
	]
	edge [
		source 53
		target 54
	]
	edge [
		source 53
		target 55
	]
	edge [
		source 53
		target 57
	]
	edge [
		source 53
		target 58
	]
	edge [
		source 7
		target 8
	]
	edge [
		source 7
		target 59
	]
	edge [
		source 7
		target 74
	]
	edge [
		source 10
		target 11
	]
	edge [
		source 10
		target 12
	]
	edge [
		source 14
		target 15
	]
	edge [
		source 14
		target 17
	]
	edge [
		source 20
		target 21
	]
	edge [
		source 20
		target 22
	]
	edge [
		source 20
		target 75
	]
	edge [
		source 23
		target 24
	]
	edge [
		source 23
		target 26
	]
	edge [
		source 23
		target 36
	]
	edge [
		source 37
		target 38
	]
	edge [
		source 37
		target 39
	]
	edge [
		source 47
		target 48
	]
	edge [
		source 55
		target 56
	]
	edge [
		source 8
		target 9
	]
	edge [
		source 59
		target 60
	]
	edge [
		source 12
		target 13
	]
	edge [
		source 15
		target 16
	]
	edge [
		source 17
		target 18
	]
	edge [
		source 24
		target 25
	]
	edge [
		source 24
		target 76
	]
	edge [
		source 24
		target 78
	]
	edge [
		source 24
		target 81
	]
	edge [
		source 26
		target 27
	]
	edge [
		source 26
		target 28
	]
	edge [
		source 39
		target 40
	]
	edge [
		source 39
		target 41
	]
	edge [
		source 39
		target 42
	]
	edge [
		source 60
		target 61
	]
	edge [
		source 60
		target 63
	]
	edge [
		source 76
		target 77
	]
	edge [
		source 78
		target 79
	]
	edge [
		source 78
		target 80
	]
	edge [
		source 81
		target 82
	]
	edge [
		source 81
		target 84
	]
	edge [
		source 81
		target 86
	]
	edge [
		source 28
		target 29
	]
	edge [
		source 28
		target 30
	]
	edge [
		source 28
		target 87
	]
	edge [
		source 42
		target 43
	]
	edge [
		source 42
		target 44
	]
	edge [
		source 61
		target 62
	]
	edge [
		source 63
		target 64
	]
	edge [
		source 63
		target 65
	]
	edge [
		source 82
		target 83
	]
	edge [
		source 84
		target 85
	]
	edge [
		source 30
		target 31
	]
	edge [
		source 30
		target 34
	]
	edge [
		source 87
		target 88
	]
	edge [
		source 65
		target 66
	]
	edge [
		source 65
		target 72
	]
	edge [
		source 31
		target 32
	]
	edge [
		source 34
		target 35
	]
	edge [
		source 66
		target 67
	]
	edge [
		source 66
		target 69
	]
	edge [
		source 72
		target 73
	]
	edge [
		source 32
		target 33
	]
	edge [
		source 67
		target 68
	]
	edge [
		source 69
		target 70
	]
	edge [
		source 69
		target 71
	]
]
